name: smart_campus_companion
description: A mobile app for university campus navigation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Networking
  dio: ^5.4.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4

  # Local Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # Auth & Security
  local_auth: ^2.2.0

  # Notifications

  # Sensors & Hardware
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  image_picker: ^1.0.7
  sensors_plus: ^4.0.2
  permission_handler: ^11.3.1

  # UI
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true