dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.4.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4

  # Local Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # Auth & Security
  local_auth: ^2.2.0           # Biometrics (F1.3)

  # Notifications
  flutter_local_notifications: ^17.2.0   # F4.1
  workmanager: ^0.5.2                    # F4.3

  # Sensors & Hardware
  geolocator: ^11.0.0          # F3.2
  google_maps_flutter: ^2.6.0  # F3.2
  image_picker: ^1.0.7         # F3.1
  sensors_plus: ^4.0.2         # F3.3
  connectivity_plus: ^6.0.3    # F2.3
  permission_handler: ^11.3.1  # NF5

  # UI
  cached_network_image: ^3.3.1  # NF2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1